# Please don't edit this file, and use the version generated at
# http://rainboard.laas.fr/project/hpp-corbaserver/.gitlab-ci.yml

variables:
  GIT_SUBMODULE_STRATEGY: "recursive"
  CCACHE_BASEDIR: "${CI_PROJECT_DIR}"
  CCACHE_DIR: "${CI_PROJECT_DIR}/ccache"

cache:
  paths:
    - ccache

.robotpkg-hpp-corbaserver: &robotpkg-hpp-corbaserver
  except:
    - gh-pages
  script:
    - mkdir -p ccache
    - cd /root/robotpkg/path
    - git pull
    - cd hpp-corbaserver
    - make checkout MASTER_REPOSITORY="dir ${CI_PROJECT_DIR}"
    - make install
    - cd work.$(hostname)/$(make show-var VARNAME=DISTNAME)/build

robotpkg-hpp-corbaserver-16.04-release:
  <<: *robotpkg-hpp-corbaserver
  image: eur0c.laas.fr:5000/humanoid-path-planner/hpp-corbaserver/hpp-corbaserver:16.04

robotpkg-hpp-corbaserver-18.04-release:
  <<: *robotpkg-hpp-corbaserver
  image: eur0c.laas.fr:5000/humanoid-path-planner/hpp-corbaserver/hpp-corbaserver:18.04

doc-coverage:
  <<: *robotpkg-hpp-corbaserver
  image: eur0c.laas.fr:5000/humanoid-path-planner/hpp-corbaserver/hpp-corbaserver:16.04
  before_script:
    - echo -e 'CXXFLAGS+= --coverage\nLDFLAGS+= --coverage\nPKG_DEFAULT_OPTIONS= debug' >> /opt/openrobots/etc/robotpkg.conf
  after_script:
    - cd /root/robotpkg/path/hpp-corbaserver
    - cd work.$(hostname)/$(make show-var VARNAME=DISTNAME)/build
    - make doc
    - mv doc/doxygen-html ${CI_PROJECT_DIR}
  artifacts:
    expire_in: 1 day
    paths:
      - doxygen-html/
      - coverage/
